[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "app"
version = "0.1.0"

dependencies = [
    "flask>=3.0.0",
    "flake8>=7.0.0",
    "unittest"
]
