name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout
      - name: Set up python
        id: setup-python
        uses: actions/setup-python
        with:
          python-version: '3.12'
      - name: Run tests
        run: |
          pip install -e .
          python -m unittest test